### ISSUE TITLE
moonrise and moonset in onecall daily

### ISSUE THREAD

**Issue by pnoe** [Prominence/openweathermap-java-api#20]
Hi,
in  model/onecall/current/Daily.java 
I can't find moonrise and moonset times.
In OWM onecall api I see :
"daily": [
    {
      "dt": 1618308000,
      "sunrise": 1618282134,
      "sunset": 1618333901,
      "moonrise": 1618284960,
      "moonset": 1618339740,
      "moon_phase": 0.04,
Am I again lost or are these values not already coded ?

**Comment by Prominence** [comment]
Hi. Probably I missed these fields or they have been added to API after my implementation. If it is critical I could make a patch and release 2.2.1 version.
By the way, thanks for your attention to my project :)

**Comment by pnoe** [comment]
Hi, it is not critical at all ! The moon can wait.
Bye.

**Comment by Prominence** [comment]
Implemented in **2.3.0** release.
