### ISSUE TITLE
Return iconUrl as https

### ISSUE THREAD

**Issue by selbiselbi** [Prominence/openweathermap-java-api#38]
Hello,

it would be nice for the iconUrl to return the https url.

That way, instead of having http://openweathermap.org/img/w/10d.png, we would have https://openweathermap.org/img/w/10d.png

So, we could either update the base url to point to https scheme, or add another method `getSecureIconUrl(String iconId)`. Or even change the method signature to `getIconUrl(String iconId, boolean secure)`. 

I can create a pull request for that if you want. Depending on what implementation you prefer.

**Comment by Prominence** [comment]
Hello. Your proposal is good. I could apply the changes to the `dev` branch, but I don't know when it should be ready for release.
Both variants are nice, but I think I'll choose the second one with method overloading.

As I said, I could made the changes by myself. But I don't know when I'll release the next version(there are a lot of changes).

**Comment by selbiselbi** [comment]
Alright, I'll let you decide then 👍

**Comment by Prominence** [comment]
Decided to return an icon URL with `https` protocol by default. As the method return String type, the use can call `replace` method to change protocol type if he wish.
For the API call it will be possible to change the protocol via `OpenWeatherMapClient#useInsecureConnection` method.

Will be available in future 3.0.0 release.
