### ISSUE TITLE
[BUG] Correct scope junit platform dependency

### ISSUE THREAD

**Issue by marcinsendyka** [Prominence/openweathermap-java-api#56]
<dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-runner</artifactId>
            <version>1.8.2</version>
        </dependency>

Should has scope test. Scope compile makes difficult to use openweathermap-java-api without maven exclusions.

**Comment by Prominence** [comment]
You are right, but the problem is on `master` branch only. Current development is on `dev` branch now, where the problem is already solved:
```
testImplementation 'org.junit.platform:junit-platform-runner:1.9.0'
```

I hope I'll find some free time to release the new version soon :)
